name = "SecondRepo"
uuid = "b26ca37d-4564-4797-9fe2-50a305df46c5"
authors = ["Nikhil <nkakarla@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
